import { AllNotesPositionsType } from "./types";

const NOTES = ["do", "re", "mi", "fa", "sol", "la", "si"];
const CLEF = ["treble", "bass"]; //Treble Clef -> clave de SOL, Bass Clef -> clave de FA

const ALL_NOTES_POSITIONS: AllNotesPositionsType = {
	do: {
		treble: {
			bottom: {
				id: 0,
				outsideBottom: true,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
			mid: {
				id: 1,
				outsideBottom: false,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: false,
			},
			top: {
				id: 2,
				outsideBottom: false,
				outsideTop: true,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
		},
		bass: {
			bottom: {
				id: 3,
				outsideBottom: true,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
			mid: {
				id: 4,
				outsideBottom: false,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: false,
			},
			top: {
				id: 5,
				outsideBottom: false,
				outsideTop: true,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
		},
	},
	re: {
		treble: {
			bottom: {
				id: 6,
				outsideBottom: false,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: false,
			},
			mid: {
				id: 7,
				outsideBottom: false,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: false,
			},
			top: {
				id: 8,
				outsideBottom: false,
				outsideTop: true,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
		},
		bass: {
			bottom: {
				id: 9,
				outsideBottom: true,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
			mid: {
				id: 10,
				outsideBottom: false,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: false,
			},
			top: {
				id: 11,
				outsideBottom: false,
				outsideTop: true,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
		},
	},
	mi: {
		treble: {
			bottom: {
				id: 12,
				outsideBottom: true,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
			mid: {
				id: 13,
				outsideBottom: false,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: false,
			},
		},
		bass: {
			bottom: {
				id: 15,
				outsideBottom: true,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
			mid: {
				id: 16,
				outsideBottom: false,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: false,
			},
			top: {
				id: 17,
				outsideBottom: false,
				outsideTop: true,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
		},
	},
	fa: {
		treble: {
			bottom: {
				id: 18,
				outsideBottom: true,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
			mid: {
				id: 19,
				outsideBottom: false,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: false,
			},
		},
		bass: {
			bottom: {
				id: 21,
				outsideBottom: true,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
			mid: {
				id: 22,
				outsideBottom: false,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: false,
			},
		},
	},
	sol: {
		treble: {
			bottom: {
				id: 24,
				outsideBottom: true,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
			mid: {
				id: 25,
				outsideBottom: false,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: false,
			},
		},
		bass: {
			bottom: {
				id: 27,
				outsideBottom: true,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
			mid: {
				id: 28,
				outsideBottom: false,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: false,
			},
		},
	},
	la: {
		treble: {
			bottom: {
				id: 30,
				outsideBottom: true,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
			mid: {
				id: 31,
				outsideBottom: false,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: false,
			},
			top: {
				id: 32,
				outsideBottom: false,
				outsideTop: true,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
		},
		bass: {
			bottom: {
				id: 33,
				outsideBottom: true,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
			mid: {
				id: 34,
				outsideBottom: false,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: false,
			},
		},
	},
	si: {
		treble: {
			bottom: {
				id: 36,
				outsideBottom: true,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
			mid: {
				id: 37,
				outsideBottom: false,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: false,
			},
			top: {
				id: 38,
				outsideBottom: false,
				outsideTop: true,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
		},
		bass: {
			bottom: {
				id: 39,
				outsideBottom: true,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
			mid: {
				id: 40,
				outsideBottom: false,
				outsideTop: false,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: false,
			},
			top: {
				id: 41,
				outsideBottom: false,
				outsideTop: true,
				aboveExtraLine: false,
				belowExtraLine: false,
				onExtraLine: true,
			},
		},
	},
};

export { NOTES, CLEF, ALL_NOTES_POSITIONS };
